### ISSUE TITLE
Agent can try to post huge number of metrics with just default collectors enabled

### ISSUE THREAD

**Issue by bspindler** [Netuitive/netuitive-diamond#25]
I have a CoreOS host running the agent as a docker container.  When the VMStatCollector is enabled some hosts can discover huge numbers of metrics - 96k in our case.

The error reported is: 

> [2017-04-24 07:40:54,728] [MainThread] error posting payload to api ingest endpoint (https://api.eu.netuitive.com/ingest/infrastructure): the dkr09xxx.xxx.xxx.xxx element has 95234 metrics. the max is 10000 metrics.
> Traceback (most recent call last):
>   File "/opt/netuitive-agent/embedded/lib/python2.7/site-packages/netuitive-0.2.2-py2.7.egg/netuitive/client.py", line 104, in post
>     raise Exception(errmsg)
> Exception: the dkr09xxx.xxx.xxx.xxx element has 95234 metrics. the max is 10000 metrics.
> [2017-04-24 07:40:54,773] [MainThread] the dkr09xxx.xxx.xxx.xxx element has 95234 metrics. the max is 10000 metrics.

  
Workaround is to disable collector: 
```
 [[VMStatCollector]]
enabled = False
```

**Comment by Grumblesmith** [comment]
After reviewing with @bspindler it looks like either VMStatCollector or NetworkCollector are the likely culprits here. NetuitiveDockerCollector was also disabled as part of the troubleshooting. The metric list grew by 55 metrics in the second jump past 10000 metrics.

**Comment by bspindler** [comment]
We found two netuitive-agent containers running at the same time on that host, this may have caused the issue.  I think we can close for now, the agent has been running fine since removing the erroneous container.
