### ISSUE TITLE
Log file handlers left open after rotation

### ISSUE THREAD

**Issue by Grumblesmith** [Netuitive/netuitive-diamond#63]
File handles are sometimes being left open for logs. Initial investigation indicated this is because all the agent processes are writing to the log file, and that concurrency isn't being handled well by the TimedRotatingFileHandler.

**Comment by TheConnMan** [comment]
Looks related to this issue: http://thinlight.org/2011/08/10/python-logging-from-multiple-processes/

**Comment by TheConnMan** [comment]
The logging handler we use is OOTB from Python. Also, the upstream Diamond project has not changed the timedrotating.py file at all.

As this is a minor, I recommend either opening an issue on the upstream Diamond project to try getting some more experienced eyes on it or using a new logging handler altogether.

**Comment by TheConnMan** [comment]
We're going to install a pure Diamond agent and see if we get the same issue.

**Comment by TheConnMan** [comment]
Issue opened on the Diamond project: https://github.com/python-diamond/Diamond/issues/720

**Comment by codytipton** [comment]
Fixed by https://github.com/Netuitive/omnibus-netuitive-agent/commit/934a295d42803198c3003e1014eff8245fd0ccbe
