### ISSUE TITLE
Elasticsearch collector SSL certificate verification should be an optional config

### ISSUE THREAD

**Issue by rclagett** [Netuitive/netuitive-diamond#68]

**Comment by TheConnMan** [comment]
@rclagett No need to create an issue if you're going to immediately open a PR against it. Just have a rich description in the PR.

**Comment by Grumblesmith** [comment]
Is this different from #65?

**Comment by rclagett** [comment]
Whoops. They are the same. I forgot I had already created an issue for this. I'll close #68 in favor of #65
