### ISSUE TITLE
Netuitive Docker Collector blkio_stats Exceptions

### ISSUE THREAD

**Issue by TheConnMan** [Netuitive/netuitive-diamond#76]
`blkio_stats` values are not floats, they're collections of objects in `Docker version 17.05.0-ce, build 89658be` which errors out the following code:

https://github.com/Netuitive/netuitive-diamond/blob/8ee12af73eb183fbc452a6641937dc4bcadeffce/src/collectors/netuitivedocker/netuitivedocker.py#L103-L107

**Comment by rclagett** [comment]
@TheConnMan Did #75 address this?

**Comment by TheConnMan** [comment]
Looks like it may have, yeah.
